imports:
  - config.yaml

parameters:
  databricks:
    address: https://westeurope.azuredatabricks.net
    cluster_id: '[Your PROD cluster ID]'
    workspace:
      base_dir: '/daipedemo'

  datalakebundle:
    notebook:
      display:
        enabled: False
