imports:
  - config.yaml

parameters:
  databricks:
    address: 'https://adb-8328309645514519.19.azuredatabricks.net/'
    repo:
      base_dir: "/Repos/{repo_name}/{tag_name}"
    job:
      suffix: "{repo_name} ({tag_name})"

  datalakebundle:
    notebook:
      display:
        enabled: False
