imports:
  - config.yaml

parameters:
  databricks:
    address: '[Your workspace address]'
    workspace:
      base_dir: '/daipedemo'
  datalakebundle:
    notebook:
      display:
        enabled: False
