imports:
  - config.yaml

parameters:
  databricks:
    address: '[Your workspace address]'
    repo:
      base_dir: "/Repos/{repo_name}/{branch_name}"
    job:
      suffix: "{repo_name} ({branch_name})"
