#!/bin/bash

ENV=$(basename "$0")

BRANCH_NAME=$1
REPO_NAME=$2

daipe dbx:job:create-or-update etl_orchestration --env="$ENV" --branch_name="$BRANCH_NAME" --repo_name="$REPO_NAME"
daipe dbx:job:create-or-update retraining_pipeline --env="$ENV" --branch_name="$BRANCH_NAME" --repo_name="$REPO_NAME"
daipe dbx:job:create-or-update feature_orchestration --env="$ENV" --branch_name="$BRANCH_NAME" --repo_name="$REPO_NAME"
daipe dbx:job:create-or-update predictions --env="$ENV" --branch_name="$BRANCH_NAME" --repo_name="$REPO_NAME"
