name: Deploy jobs to prod
on:
  release:
    types: [published]

jobs:
  build:
    uses: daipe-ai/daipe-project-ci-cd/.github/workflows/build.yml@v1

  deploy:
    needs: build
    uses: daipe-ai/daipe-project-ci-cd/.github/workflows/run_command.yml@v1
    with:
      command: daipe dbx:job:create-all --env=prod --repo_name=${{ github.event.repository.name }} --branch_name=${{ github.head_ref }}
      env: prod
    secrets:
      DBX_URL: ${{ secrets.DBX_URL }}
      DBX_TOKEN: ${{ secrets.DBX_TOKEN }}
