name: Test pipeline
on:
  pull_request:

jobs:
  build:
    uses: daipe-ai/daipe-demo-databricks/.github/workflows/build.yml@master

  deploy:
    needs: build
    uses: daipe-ai/daipe-demo-databricks/.github/workflows/run_command.yml@master
    with:
      command: bash ./jobs/test ${{ github.head_ref }} ${{ github.event.repository.name }}
      env: test
    secrets:
      DBX_URL: ${{ secrets.DBX_URL }}
      DBX_TOKEN: ${{ secrets.DBX_TOKEN }}
