name: promote_model
on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'The name of the model in Mlflow'     
        required: true
        type: string

jobs:
  promote_model:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_TOKEN: ${{ secrets.DBX_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: install_mlflow
        run: |
          pip install mlflow

      - name: promote
        run: |
          python src/daipedemo/mlops/promote_model.py {{ inputs.model_name }}
